seed_data_persons = '''
INSERT INTO persons
  (first_name, middle_names, last_name, maiden_name, suffix, nickname, display_name,
  sex, birth_date, birth_date_precision)
VALUES
  ('Anthony', NULL, 'Franzonello', NULL, 2, 'Tony', NULL, 'm', '1948-02-09', 'day'), 
  ('Mary', 'Elizabeth', 'Franzonello', 'Clavin', NULL, NULL, NULL, 'f', '1948-11-02', 'day'), 
  ('Michael', NULL, 'Sirilla', NULL, NULL, 'Mike', NULL, 'm', '1970-01-07', 'day'), 
  ('David', NULL, 'Schmiesing', NULL, NULL, 'Dave', NULL, 'm', '1970-04-25', 'day'), 
  ('Kevin', 'Kyle', 'Snell', NULL, NULL, NULL, NULL, 'm', '1971-01-27', 'day'), 
  ('Justine', 'Marie', 'Schmiesing', 'Franzonello', NULL, NULL, NULL, 'f', '1972-03-31', 'day'), 
  ('Jessica', 'Ann', 'Snell', 'Franzonello', NULL, NULL, NULL, 'f', '1973-06-11', 'day'), 
  ('Anthony', 'Joseph', 'Franzonello', NULL, 3, 'Tony', NULL, 'm', '1975-02-03', 'day'), 
  ('Tara', NULL, 'Franzonello', 'Wilbur', NULL, NULL, NULL, 'f', '1977-09-08', 'day'), 
  ('Laura', 'Elizabeth', 'Sirilla', 'Franzonello', NULL, NULL, NULL, 'f', '1978-03-18', 'day'), 
  ('David', 'Michael', 'Franzonello', NULL, 1, NULL, NULL, 'm', '1980-06-11', 'day'), 
  ('Anna', 'Rachael', 'Paprocki', 'Franzonello', NULL, NULL, NULL, 'f', '1981-10-11', 'day'), 
  ('Kely', NULL, 'Franzonello', 'Bruen', NULL, NULL, NULL, 'f', '1982-01-28', 'day'), 
  ('Matthew', NULL, 'Paprocki', NULL, NULL, 'Matt', NULL, 'm', '1982-04-04', 'day'), 
  ('Michael', 'Vincent', 'Franzonello', NULL, NULL, NULL, NULL, 'm', '1985-04-25', 'day'), 
  ('Vincent', 'James', 'Franzonello', NULL, 1, NULL, NULL, 'm', '1987-04-06', 'day'), 
  ('Christopher', 'Anthony', 'Franzonello', NULL, 1, NULL, NULL, 'm', '1989-04-26', 'day'), 
  ('Emily', NULL, 'Franzonello', 'DeSana', NULL, NULL, NULL, 'f', '1989-09-10', 'day'), 
  ('Molly', NULL, 'Franzonello', 'Robinson', NULL, NULL, NULL, 'f', '1991-10-17', 'day'), 
  ('Peter', NULL, 'Rosaschi', NULL, 4, NULL, NULL, 'm', '1993-09-06', 'day'), 
  ('Molly', NULL, 'Schmiesing', 'Clarahan', NULL, NULL, NULL, 'f', '1993-10-16', 'day'), 
  ('Michael', 'David', 'Schmiesing', NULL, NULL, NULL, NULL, 'm', '1994-07-07', 'day'), 
  ('Rita', 'Marie', 'Siverio', 'Franzonello', NULL, NULL, NULL, 'f', '1994-07-22', 'day'),  
  ('Andres', NULL, 'Siverio', NULL, NULL, NULL, NULL, 'm', '1995-11-22', 'day'), 
  ('Marianna', NULL, 'Rosaschi', 'Schmiesing', NULL, NULL, NULL, 'f', '1996-05-19', 'day'), 
  ('Ryan', NULL, 'Strand', NULL, NULL, NULL, NULL, 'm', '1996-12-31', 'day'), 
  ('Benjamin', NULL, 'Harris', NULL, 1, 'Benny', NULL, 'm', '1997-02-25', 'day'), 
  ('Victoria', 'Mercedes', 'Strand', 'Snell', NULL, 'Torre', NULL, 'f', '1997-06-01', 'day'), 
  ('Kateri', 'Marie;Providence', 'Harris', 'Schmiesing', NULL, NULL, NULL, 'f', '1997-09-22', 'day'), 
  ('Justyna', NULL, 'Sirilla', NULL, NULL, NULL, NULL, 'f', '1998-12-13', 'day'), 
  ('Veronica', 'Lexus', 'Snell', NULL, NULL, NULL, NULL, 'f', '1999-12-19', 'day'), 
  ('Rachel', NULL, 'Sirilla', NULL, NULL, NULL, NULL, 'f', '2000-01-15', 'day'), 
  ('James', 'Edwin', 'Schmiesing', NULL, NULL, NULL, NULL, 'm', '2000-02-25', 'day'), 
  ('Athanasius', NULL, 'Sirilla', NULL, NULL, NULL, NULL, 'm', '2000-03-18', 'day'), 
  ('Sebastian', NULL, 'Snell', NULL, NULL, NULL, NULL, 'm', '2001-08-21', 'day'), 
  ('Augustine', NULL, 'Sirilla', NULL, NULL, 'Gus', NULL, 'm', '2001-09-01', 'day'), 
  ('Mary', 'Grace', 'Snell', 'Dimmock', NULL, NULL, NULL, 'f', '2001-12-10', 'day'), 
  ('Peter', NULL, 'Sammons', NULL, NULL, NULL, NULL, 'm', '2003-05-21', 'day'), 
  ('Anthony', 'Joseph', 'Franzonello', NULL, 4, 'Tony', NULL, 'm', '2003-05-28', 'day'), 
  ('Faith', NULL, 'Sammons', 'Sirilla', NULL, NULL, NULL, 'f', '2003-07-03', 'day'), 
  ('Maximilian', NULL, 'Snell', NULL, NULL, 'Max', NULL, 'm', '2004-03-01', 'day'), 
  ('Matthew', NULL, 'Schmiesing', NULL, NULL, 'Matt', NULL, 'm', '2004-11-16', 'day'), 
  ('Mercy', NULL, 'Franzonello', NULL, NULL, NULL, NULL, 'f', '2006-05-09', 'day'), 
  ('Constantine', NULL, 'Snell', NULL, NULL, 'Tino', NULL, 'm', '2007-01-23', 'day'), 
  ('Elizabeth', NULL, 'Schmiesing', NULL, NULL, NULL, NULL, 'f', '2007-02-14', 'day'), 
  ('Xavier', NULL, 'Franzonello', NULL, NULL, NULL, NULL, 'm', '2007-04-04', 'day'), 
  ('David', 'Michael', 'Franzonello', NULL, 2, NULL, NULL, 'm', '2007-07-31', 'day'), 
  ('Hope', NULL, 'Sirilla', NULL, NULL, NULL, NULL, 'f', '2007-08-04', 'day'), 
  ('Luciano', NULL, 'Franzonello', NULL, NULL, NULL, NULL, 'm', '2009-02-28', 'day'), 
  ('Andrew', NULL, 'Franzonello', NULL, NULL, 'Andy', NULL, 'm', '2009-04-10', 'day'), 
  ('Gabriel', NULL, 'Snell', NULL, NULL, 'Gabe', NULL, 'm', '2010-02-02', 'day'), 
  ('Charity', NULL, 'Sirilla', NULL, NULL, NULL, NULL, 'f', '2010-03-15', 'day'), 
  ('Cordia', NULL, 'Franzonello', NULL, NULL, NULL, NULL, 'f', '2010-10-14', 'day'), 
  ('Peter', NULL, 'Schmiesing', NULL, NULL, NULL, NULL, 'm', '2010-11-27', 'day'), 
  ('James', NULL, 'Franzonello', NULL, NULL, NULL, NULL, 'm', '2011-08-26', 'day'), 
  ('Aletheia', NULL, 'Sirilla', NULL, NULL, NULL, NULL, 'f', '2012-03-24', 'day'), 
  ('Vivian', NULL, 'Snell', NULL, NULL, NULL, NULL, 'f', '2013-06-07', 'day'), 
  ('Benedict', NULL, 'Franzonello', NULL, NULL, 'Benno', NULL, 'm', '2014-12-22', 'day'), 
  ('George', 'Michael', 'Sirilla', NULL, NULL, NULL, NULL, 'm', '2015-12-17', 'day'), 
  ('Leo', NULL, 'Sirilla', NULL, NULL, NULL, NULL, 'm', '2016-02-28', 'day'), 
  ('Vera', NULL, 'Snell', NULL, NULL, NULL, NULL, 'f', '2016-06-16', 'day'), 
  ('Fiona', 'Rose', 'Paprocki', NULL, NULL, NULL, NULL, 'f', '2017-06-04', 'day'), 
  ('Mary', 'Clare', 'Schmiesing', NULL, NULL, NULL, NULL, 'f', '2017-11-07', 'day'), 
  ('Jacinta', NULL, 'Franzonello', NULL, NULL, NULL, NULL, 'f', '2017-12-13', 'day'), 
  ('Lucy', NULL, 'Schmiesing', NULL, NULL, NULL, NULL, 'f', '2018-10-23', 'day'), 
  ('Simeon', NULL, 'Snell', NULL, NULL, NULL, NULL, 'm', '2019-02-18', 'day'), 
  ('Ave', NULL, 'Franzonello', NULL, NULL, NULL, NULL, 'f', '2020-02-19', 'day'), 
  ('Anne', 'Germaine', 'Franzonello', NULL, NULL, NULL, NULL, 'f', '2020-03-19', 'day'), 
  ('Amelia', NULL, 'Sirilla', NULL, NULL, NULL, NULL, 'f', '2020-10-13', 'day'), 
  ('Peter', NULL, 'Paprocki', NULL, NULL, NULL, NULL, 'm', '2021-06-17', 'day'), 
  ('Judah', NULL, 'Siverio', NULL, NULL, NULL, NULL, 'm', '2021-11-08', 'day'), 
  ('Christopher', NULL, 'Franzonello', NULL, 2, NULL, NULL, 'm', '2021-12-13', 'day'), 
  ('Vincent', 'Bonaventure', 'Franzonello', NULL, 2, 'Bono', NULL, 'm', '2022-01-13', 'day'), 
  ('Cyprian', NULL, 'Sirilla', NULL, NULL, NULL, NULL, 'm', '2022-07-09', 'day'), 
  ('Benjamin', NULL, 'Harris', NULL, 2, 'Benny', NULL, 'm', '2022-09-27', 'day'), 
  ('Dominic', NULL, 'Sirilla', NULL, NULL, NULL, NULL, 'm', '2022-11-24', 'day'), 
  ('Edith', NULL, 'Schmiesing', NULL, NULL, NULL, NULL, 'f', '2023-03-03', 'day'), 
  ('Francesco', NULL, 'Franzonello', NULL, NULL, NULL, NULL, 'm', '2023-11-14', 'day'), 
  ('Felice', NULL, 'Franzonello', NULL, NULL, NULL, NULL, 'f', '2023-12-05', 'day'), 
  ('Esther', NULL, 'Schmiesing', NULL, NULL, NULL, NULL, 'f', '2024-03-24', 'day'), 
  ('Francesca', NULL, 'Franzonello', NULL, NULL, NULL, NULL, 'f', '2024-05-05', 'day'), 
  ('Josephine', NULL, 'Sirilla', NULL, NULL, NULL, NULL, 'f', '2024-08-23', 'day'), 
  ('John', NULL, 'Harris', NULL, NULL, NULL, NULL, 'm', '2025-01-21', 'day'), 
  ('Leo', NULL, 'Harris', NULL, NULL, NULL, NULL, 'm', '2025-01-21', 'day'), 
  ('Polycarp', NULL, 'Sirilla', NULL, NULL, 'Paul', NULL, 'm', '2025-03-07', 'day'), 
  ('Peter', NULL, 'Rosaschi', NULL, 5, NULL, NULL, 'm', '2025-06-14', 'day'), 
  (NULL, NULL, 'Franzonello', NULL, NULL, NULL, NULL, NULL, '2025-12-31', 'year'), 
  (NULL, NULL, 'Siverio', NULL, NULL, NULL, NULL, NULL, '2026-12-31', 'year');
'''

seed_union_data = '''
INSERT INTO marriages (husband_id, wife_id, wedding_date)
  VALUES
  ((SELECT person_id FROM persons WHERE first_name = 'Anthony' AND last_name = 'Franzonello' AND suffix = 2),
   (SELECT person_id FROM persons WHERE first_name = 'Mary' AND last_name = 'Franzonello'),
   '1971-06-12'),

  ((SELECT person_id FROM persons WHERE first_name = 'David' AND last_name = 'Schmiesing'),
   (SELECT person_id FROM persons WHERE first_name = 'Justine' AND last_name = 'Schmiesing'),
   '1993-07-19'),

  ((SELECT person_id FROM persons WHERE first_name = 'Kevin' AND last_name = 'Snell'),
   (SELECT person_id FROM persons WHERE first_name = 'Jessica' AND last_name = 'Snell'),
   '1995-05-20'),

  ((SELECT person_id FROM persons WHERE first_name = 'Anthony' AND last_name = 'Franzonello' AND suffix = 3),
   (SELECT person_id FROM persons WHERE first_name = 'Tara' AND last_name = 'Franzonello'),
   '2000-08-12'),

  ((SELECT person_id FROM persons WHERE first_name = 'Michael' AND last_name = 'Sirilla'),
   (SELECT person_id FROM persons WHERE first_name = 'Laura' AND last_name = 'Sirilla'),
   '1999-07-31'),

  ((SELECT person_id FROM persons WHERE first_name = 'David' AND last_name = 'Franzonello' AND suffix = 1),
   (SELECT person_id FROM persons WHERE first_name = 'Kely' AND last_name = 'Franzonello'),
   '2005-06-05'),
  
  ((SELECT person_id FROM persons WHERE first_name = 'Matthew' AND last_name = 'Paprocki'),
   (SELECT person_id FROM persons WHERE first_name = 'Anna' AND last_name = 'Paprocki'),
   '2014-11-01'),

  ((SELECT person_id FROM persons WHERE first_name = 'Vincent' AND last_name = 'Franzonello' AND suffix = 1),
   (SELECT person_id FROM persons WHERE first_name = 'Molly' AND last_name = 'Franzonello'),
   '2019-08-31'),

  ((SELECT person_id FROM persons WHERE first_name = 'Christopher' AND last_name = 'Franzonello' AND suffix = 1),
   (SELECT person_id FROM persons WHERE first_name = 'Emily' AND last_name = 'Franzonello'),
   '2016-09-24'),

  ((SELECT person_id FROM persons WHERE first_name = 'Andres' AND last_name = 'Siverio'),
   (SELECT person_id FROM persons WHERE first_name = 'Rita' AND last_name = 'Siverio'),
   '2024-04-27'),

  ((SELECT person_id FROM persons WHERE first_name = 'Michael' AND last_name = 'Schmiesing'),
   (SELECT person_id FROM persons WHERE first_name = 'Molly' AND last_name = 'Schmiesing'),
   '2016-08-06'),

  ((SELECT person_id FROM persons WHERE first_name = 'Peter' AND last_name = 'Rosaschi' AND suffix = 4),
   (SELECT person_id FROM persons WHERE first_name = 'Marianna' AND last_name = 'Rosaschi'),
   '2024-08-03'),

  ((SELECT person_id FROM persons WHERE first_name = 'Benjamin' AND last_name = 'Harris' AND suffix = 1),
   (SELECT person_id FROM persons WHERE first_name = 'Kateri' AND last_name = 'Harris'),
   '2020-05-23'),

  ((SELECT person_id FROM persons WHERE first_name = 'Athanasius' AND last_name = 'Sirilla'),
   (SELECT person_id FROM persons WHERE first_name = 'Justyna' AND last_name = 'Sirilla'),
   '2021-07-03'),

  ((SELECT person_id FROM persons WHERE first_name = 'Augustine' AND last_name = 'Sirilla'),
   (SELECT person_id FROM persons WHERE first_name = 'Rachel' AND last_name = 'Sirilla'),
   '2024-12-14'),

  ((SELECT person_id FROM persons WHERE first_name = 'Peter' AND last_name = 'Sammons'),
   (SELECT person_id FROM persons WHERE first_name = 'Faith' AND last_name = 'Sammons'),
   '2025-05-17'),

  ((SELECT person_id FROM persons WHERE first_name = 'Ryan' AND last_name = 'Strand'),
   (SELECT person_id FROM persons WHERE first_name = 'Victoria' AND last_name = 'Strand'),
   '2025-09-20'),

  ((SELECT person_id FROM persons WHERE first_name = 'Sebastian' AND last_name = 'Snell'),
   (SELECT person_id FROM persons WHERE first_name = 'Mary' AND last_name = 'Snell'),
   '2024-09-07');
'''

seed_folders_data_2025 = '''
INSERT INTO folders (person_id, folder_name, project_year) VALUES
  ((SELECT person_id FROM persons WHERE first_name = 'Anna' AND last_name = 'Franzonello'), 'Anna', 2025),
  ((SELECT person_id FROM persons WHERE first_name = 'Athanasius' AND last_name = 'Sirilla'), 'Athanasius', 2025),
  ((SELECT person_id FROM persons WHERE first_name = 'Augustine' AND last_name = 'Sirilla'), 'Augustine', 2025),
  ((SELECT person_id FROM persons WHERE first_name = 'Christopher' AND last_name = 'Franzonello' AND suffix = 1), 'Christopher', 2025),
  ((SELECT person_id FROM persons WHERE first_name = 'Anthony' AND last_name = 'Franzonello' AND suffix = 2), 'Dad', 2025),
  ((SELECT person_id FROM persons WHERE first_name = 'David' AND last_name = 'Franzonello' AND suffix = 1), 'David', 2025),
  (NULL, 'Drone', 2025),
  ((SELECT person_id FROM persons WHERE first_name = 'Elizabeth' AND last_name = 'Schmiesing'), 'Elizabeth', 2025),
  ((SELECT person_id FROM persons WHERE first_name = 'Faith' AND last_name = 'Sirilla'), 'Faith', 2025),
  ((SELECT person_id FROM persons WHERE first_name = 'Hope' AND last_name = 'Sirilla'), 'Hope', 2025),
  ((SELECT person_id FROM persons WHERE first_name = 'James' AND last_name = 'Schmiesing'), 'James', 2025),
  ((SELECT person_id FROM persons WHERE first_name = 'Jessica' AND last_name = 'Franzonello'), 'Jessica', 2025),
  ((SELECT person_id FROM persons WHERE first_name = 'Justine' AND last_name = 'Franzonello'), 'Justine', 2025),
  ((SELECT person_id FROM persons WHERE first_name = 'Kateri' AND last_name = 'Schmiesing'), 'Kateri', 2025),
  ((SELECT person_id FROM persons WHERE first_name = 'Kely' AND last_name = 'Bruen'), 'Kely', 2025),
  ((SELECT person_id FROM persons WHERE first_name = 'Kevin' AND last_name = 'Snell'), 'Kevin', 2025),
  ((SELECT person_id FROM persons WHERE first_name = 'Laura' AND last_name = 'Franzonello'), 'Laura', 2025),
  ((SELECT person_id FROM persons WHERE first_name = 'Marianna' AND last_name = 'Schmiesing'), 'Marianna', 2025),
  ((SELECT person_id FROM persons WHERE first_name = 'Matthew' AND last_name = 'Schmiesing'), 'Matthew', 2025),
  ((SELECT person_id FROM persons WHERE first_name = 'Maximilian' AND last_name = 'Snell'), 'Max', 2025),
  ((SELECT person_id FROM persons WHERE first_name = 'Mercy' AND last_name = 'Franzonello'), 'Mercy', 2025),
  ((SELECT person_id FROM persons WHERE first_name = 'Michael' AND last_name = 'Franzonello'), 'Michael', 2025),
  ((SELECT person_id FROM persons WHERE first_name = 'Molly' AND last_name = 'Clarahan'), 'Mike & Molly', 2025),
  ((SELECT person_id FROM persons WHERE first_name = 'Molly' AND last_name = 'Robinson'), 'Molly', 2025),
  ((SELECT person_id FROM persons WHERE first_name = 'Mary' AND last_name = 'Clavin'), 'Mom', 2025),
  (NULL, 'Other', 2025),
  ((SELECT person_id FROM persons WHERE first_name = 'Rita' AND last_name = 'Franzonello'), 'Rita', 2025),
  ((SELECT person_id FROM persons WHERE first_name = 'Ryan' AND last_name = 'Strand'), 'Ryan', 2025),
  ((SELECT person_id FROM persons WHERE first_name = 'Sebastian' AND last_name = 'Snell'), 'Sebastian', 2025),
  ((SELECT person_id FROM persons WHERE first_name = 'Constantine' AND last_name = 'Snell'), 'Tino', 2025),
  ((SELECT person_id FROM persons WHERE first_name = 'Anthony' AND last_name = 'Franzonello' AND suffix = 3), 'Tony', 2025),
  ((SELECT person_id FROM persons WHERE first_name = 'Anthony' AND last_name = 'Franzonello' AND suffix = 4), 'Tony IV', 2025),
  ((SELECT person_id FROM persons WHERE first_name = 'Veronica' AND last_name = 'Snell'), 'Veronica', 2025),
  ((SELECT person_id FROM persons WHERE first_name = 'Victoria' AND last_name = 'Snell'), 'Victoria', 2025),
  ((SELECT person_id FROM persons WHERE first_name = 'Vincent' AND last_name = 'Franzonello' AND suffix = 1), 'Vincent', 2025),
  ((SELECT person_id FROM persons WHERE first_name = 'Xavier' AND last_name = 'Franzonello'), 'Xavier', 2025)
  ;

INSERT INTO folders (animal_id, folder_name, project_year) VALUES
  ((SELECT animal_id FROM animals WHERE first_name = 'Mobius'), 'Mobi', 2025)
  ;
'''