[microsoft.urls]
identity = "https://login.microsoftonline.com/common/oauth2/v2.0"

[microsoft.oauth]
redirect_uri = "http://localhost:5000/authorize/azure/callback"

[onedrive.urls]
graph = "https://graph.microsoft.com/v1.0"

[onedrive.oauth]
scopes = ["User.Read", "Files.ReadWrite", "offline_access"]

[onedrive.limits]
rate = 5

[google.urls]
authorize = "https://accounts.google.com/o/oauth2/v2/auth"
token = "https://oauth2.googleapis.com/token"

[google_drive.urls]
api = "https://www.googleapis.com/drive/v3"

[google_drive.oauth]
scopes = ["https://www.googleapis.com/auth/drive"]

[gmail.urls]
api = "https://gmail.googleapis.com/gmail/v1"

[gmail.oauth]
scopes = ["https://www.googleapis.com/auth/gmail.compose"]

[google_calendar.urls]
api = "https://www.googleapis.com/calendar/v3"

[google_calendar.oauth]
scopes = ["https://www.googleapis.com/auth/calendar.events"]

[github.urls]
api = "https://api.github.com"
